@endpoint = http://localhost:5110

### Gets a list of users without tracking changes to the entities.
GET {{endpoint}}/users/
Accept: application/json

### Gets a list of users with tracking changes to the entities.
GET {{endpoint}}/users?asTracking=true
Accept: application/json

### Gets a user by their unique identifier.
GET {{endpoint}}/users/fe93ffba-29ac-4d2e-0a0f-08de8c0c7f12
Accept: application/json

### Gets a list of users with their posts.
GET {{endpoint}}/users/posts?lastUserId=0062b2e9-1a35-4199-0ed4-08de8c0c7f12
Accept: application/json

### Gets a user profile page by their unique identifier.
GET {{endpoint}}/users/0062b2e9-1a35-4199-0ed4-08de8c0c7f12/profile
Accept: application/json

### Gets a list of users with their most used tags
GET {{endpoint}}/users/tags/aggregation?lastUserId=001ca392-4326-41c3-11f4-08de8c0c7f12
Accept: application/json

### Gets a list of most used tags.
GET {{endpoint}}/tags/most-used?topN=5
Accept: application/json

